### ISSUE TITLE
Incorrect immediacy of some words

### ISSUE THREAD

**Issue by ruv** [mpgirro/atom-language-forth#8]
[`IMMEDIATE`](https://forth-standard.org/standard/core/IMMEDIATE) is an ordinary word in Forth (i.e., it isn't immediate), but it is declared as immediate in [forth.cson](https://github.com/mpgirro/atom-language-forth/blob/5d87fe0a692654dbe5ab01849d0ac58b7f2994bb/grammars/forth.cson#L147).

Gforth specific `COMPILE-ONLY` and `RESTRICT` are also ordinary words.

Would you like to correct thees issues?

**Comment by mpgirro** [comment]
Thank you for your input. I've fixed the issue and release a new version. 

Let me know if you find anything else.
